"""initial_schema_with_13_tables

Revision ID: ba9298710d81
Revises: 
Create Date: 2026-04-18 14:59:43.354785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba9298710d81'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('salts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Unique salt identifier'),
    sa.Column('formula_name', sa.String(length=100), nullable=False, comment="Scientific/Generic name (e.g., 'Paracetamol', 'Amoxicillin')"),
    sa.Column('description', sa.Text(), nullable=True, comment="Detailed description of the salt's pharmacological properties"),
    sa.Column('category', sa.String(length=50), nullable=False, comment="Therapeutic category (e.g., 'Analgesic', 'Antibiotic', 'ORS')"),
    sa.Column('atc_code', sa.String(length=20), nullable=True, comment='WHO Anatomical Therapeutic Chemical classification code'),
    sa.Column('dosage_form', sa.String(length=50), nullable=True, comment="Standard dosage form (e.g., 'Tablet', 'Syrup', 'Capsule')"),
    sa.Column('standard_strength', sa.String(length=50), nullable=True, comment="Standard potency (e.g., '500mg', '250mg/5ml')"),
    sa.Column('unit_of_measure', sa.String(length=20), server_default='units', nullable=False, comment="Standard unit for quantity (e.g., 'tablets', 'bottles', 'vials', 'strips')"),
    sa.Column('abc_class', sa.Enum('A', 'B', 'C', name='abcclass'), nullable=False, comment='ABC inventory classification: A=critical, B=moderate, C=low-priority'),
    sa.Column('reorder_level', sa.Integer(), nullable=True, comment='Minimum stock level that triggers a reorder. Calculated as: (avg_daily_usage x lead_time_days) + safety_stock'),
    sa.Column('safety_stock', sa.Integer(), nullable=True, comment='Buffer stock to prevent stockouts during supply delays. Typically 1-2 weeks of average usage.'),
    sa.Column('critical_threshold', sa.Integer(), nullable=True, comment='CRITICAL alert threshold. Stock at or below this level = treatment interruption risk. Triggers immediate red alert.'),
    sa.Column('warning_threshold', sa.Integer(), nullable=True, comment='WARNING alert threshold. Stock at or below this level = auto-reorder should be triggered. Yellow alert on dashboard.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Timestamp when this record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Timestamp when this record was last updated'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False, comment='Soft-delete flag. False = logically deleted.'),
    sa.PrimaryKeyConstraint('id'),
    comment='Active Pharmaceutical Ingredients (APIs). Multiple medicines share a salt → enables substitution logic. Includes reorder automation and ABC classification.'
    )
    op.create_index('ix_salt_abc_class', 'salts', ['abc_class'], unique=False)
    op.create_index(op.f('ix_salts_category'), 'salts', ['category'], unique=False)
    op.create_index(op.f('ix_salts_formula_name'), 'salts', ['formula_name'], unique=True)
    op.create_index(op.f('ix_salts_is_active'), 'salts', ['is_active'], unique=False)
    op.create_table('shops',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Unique shop identifier'),
    sa.Column('name', sa.String(length=150), nullable=False, comment='Official name of the pharmacy/facility'),
    sa.Column('code', sa.String(length=20), nullable=False, comment="Short alphanumeric code for internal reference (e.g., 'PH-NR-001')"),
    sa.Column('address', sa.Text(), nullable=True, comment='Full street address of the facility'),
    sa.Column('city', sa.String(length=100), nullable=False, comment='City for geographic grouping and climate-based predictions'),
    sa.Column('state', sa.String(length=100), nullable=True, comment='State or province'),
    sa.Column('pincode', sa.String(length=10), nullable=True, comment='PIN/ZIP code for precise geolocation mapping'),
    sa.Column('latitude', sa.Float(precision=9, asdecimal=6), nullable=True, comment='Geographic latitude for OpenWeather API calls'),
    sa.Column('longitude', sa.Float(precision=9, asdecimal=6), nullable=True, comment=' Geographic longitude for OpenWeather API calls'),
    sa.Column('contact_phone', sa.String(length=20), nullable=True, comment='Primary contact number'),
    sa.Column('contact_email', sa.String(length=255), nullable=True, comment='Contact email for notifications and redistribution alerts'),
    sa.Column('storage_capacity', sa.Integer(), nullable=True, comment='Maximum storage units the facility can hold'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Timestamp when this record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Timestamp when this record was last updated'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False, comment='Soft-delete flag. False = logically deleted.'),
    sa.PrimaryKeyConstraint('id'),
    comment='Pharmacy/healthcare facilities in the distribution network. The redistribution engine operates across these nodes.'
    )
    op.create_index(op.f('ix_shops_city'), 'shops', ['city'], unique=False)
    op.create_index(op.f('ix_shops_code'), 'shops', ['code'], unique=True)
    op.create_index(op.f('ix_shops_is_active'), 'shops', ['is_active'], unique=False)
    op.create_index(op.f('ix_shops_pincode'), 'shops', ['pincode'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Unique user identifier'),
    sa.Column('username', sa.String(length=50), nullable=False, comment='Unique login username (case-sensitive)'),
    sa.Column('email', sa.String(length=255), nullable=False, comment='User email address for notifications and recovery'),
    sa.Column('password_hash', sa.String(length=255), nullable=False, comment='Bcrypt hash of user password. NEVER store plaintext.'),
    sa.Column('full_name', sa.String(length=100), nullable=False, comment='Display name of the user'),
    sa.Column('role', sa.Enum('ADMIN', 'PHARMACIST', 'VIEWER', name='userrole'), nullable=False, comment='RBAC role: admin or pharmacist'),
    sa.Column('is_locked', sa.Boolean(), server_default='false', nullable=False, comment='Account lock flag — set after too many failed login attempts'),
    sa.Column('failed_login_attempts', sa.Integer(), server_default='0', nullable=False, comment='Counter for consecutive failed login attempts'),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp of last successful login'),
    sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp of last password change. Used to force periodic resets.'),
    sa.Column('password_changed_by', sa.String(length=20), nullable=True, comment="Who changed the password: 'self' or 'admin_reset'"),
    sa.Column('must_change_password', sa.Boolean(), server_default='false', nullable=False, comment='Force password change on next login (e.g., after admin reset)'),
    sa.Column('mfa_enabled', sa.Boolean(), server_default='false', nullable=False, comment='Two-factor authentication enabled. HIPAA 2025 recommends MFA for all ePHI access.'),
    sa.Column('mfa_secret', sa.String(length=255), nullable=True, comment='TOTP secret key for authenticator app (stored encrypted in production)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Timestamp when this record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Timestamp when this record was last updated'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False, comment='Soft-delete flag. False = logically deleted.'),
    sa.PrimaryKeyConstraint('id'),
    comment='System users with RBAC roles for authentication and authorization'
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Unique audit record identifier'),
    sa.Column('action_type', sa.Enum('STOCK_ADDED', 'STOCK_UPDATED', 'STOCK_REMOVED', 'STOCK_TRANSFERRED', 'STOCK_ADJUSTED', 'STOCK_EXPIRED', 'MEDICINE_CREATED', 'MEDICINE_UPDATED', 'MEDICINE_DELETED', 'USER_LOGIN', 'USER_LOGOUT', 'USER_CREATED', 'USER_UPDATED', 'USER_ROLE_CHANGED', 'USER_LOCKED', 'USER_UNLOCKED', 'SHOP_CREATED', 'SHOP_UPDATED', 'SYSTEM_ALERT', 'REDISTRIBUTION_TRIGGERED', 'FORECAST_GENERATED', name='action_type_enum', create_constraint=True), nullable=False, comment='Category of action performed'),
    sa.Column('description', sa.Text(), nullable=False, comment='Human-readable description of what happened'),
    sa.Column('details', sa.Text(), nullable=True, comment='JSON payload with full before/after state of the affected record'),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='User who performed the action. NULL = system action.'),
    sa.Column('ip_address', sa.String(length=45), nullable=True, comment='IP address of the client (supports IPv6 addresses)'),
    sa.Column('user_agent', sa.String(length=255), nullable=True, comment='Client user-agent string for forensic analysis'),
    sa.Column('resource_type', sa.String(length=50), nullable=True, comment="Type of affected resource (e.g., 'inventory', 'medicine', 'user')"),
    sa.Column('resource_id', sa.Integer(), nullable=True, comment='ID of the affected resource record'),
    sa.Column('sha256_hash', sa.String(length=64), nullable=False, comment='SHA-256 hash of (action_type + user_id + timestamp + details). Computed BEFORE insert. Any post-insert modification invalidates this hash.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Timestamp when this record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Timestamp when this record was last updated'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    comment='Immutable, cryptographically-hashed audit trail. Every inventory mutation and sensitive action is recorded here. INSERT ONLY — no updates or deletes permitted.'
    )
    op.create_index('ix_audit_action', 'audit_logs', ['action_type'], unique=False)
    op.create_index('ix_audit_resource', 'audit_logs', ['resource_type', 'resource_id'], unique=False)
    op.create_index('ix_audit_timestamp', 'audit_logs', ['created_at'], unique=False)
    op.create_index('ix_audit_user', 'audit_logs', ['user_id'], unique=False)
    op.create_table('climate_alerts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False, comment='Shop location affected by this climate alert'),
    sa.Column('city', sa.String(length=100), nullable=False, comment='City name from the weather data'),
    sa.Column('temperature_c', sa.Float(precision=4, asdecimal=2), nullable=False, comment='Temperature in Celsius at time of alert generation'),
    sa.Column('humidity_pct', sa.Float(precision=5, asdecimal=2), nullable=False, comment='Relative humidity percentage'),
    sa.Column('weather_condition', sa.String(length=100), nullable=True, comment="OpenWeather condition description (e.g., 'Light rain')"),
    sa.Column('risk_level', sa.Enum('LOW', 'MODERATE', 'HIGH', 'CRITICAL', name='risklevel'), nullable=False, comment='Severity classification of the health risk'),
    sa.Column('disease_risk', sa.String(length=100), nullable=False, comment="Predicted disease (e.g., 'Dengue', 'Cholera', 'Heat Stroke')"),
    sa.Column('recommended_salts', sa.Text(), nullable=True, comment='JSON array of salt_ids recommended for proactive stocking'),
    sa.Column('recommended_medicines', sa.Text(), nullable=True, comment='JSON array of medicine_ids recommended for proactive stocking'),
    sa.Column('action_summary', sa.Text(), nullable=True, comment='Human-readable summary of recommended actions'),
    sa.Column('weather_api_response', sa.Text(), nullable=True, comment='Raw JSON response from OpenWeather API (for debugging/auditing)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Timestamp when this record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Timestamp when this record was last updated'),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Weather-based health risk alerts. Produced by the Climate-Disease Engine and consumed by the dashboard for proactive stocking decisions.'
    )
    op.create_index('ix_climate_alert_date', 'climate_alerts', ['created_at'], unique=False)
    op.create_index('ix_climate_alert_risk', 'climate_alerts', ['risk_level'], unique=False)
    op.create_index('ix_climate_alert_shop', 'climate_alerts', ['shop_id'], unique=False)
    op.create_table('medicines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Unique medicine identifier'),
    sa.Column('brand_name', sa.String(length=150), nullable=False, comment="Commercial brand name (e.g., 'Crocin 500mg')"),
    sa.Column('generic_name', sa.String(length=150), nullable=True, comment='Generic display name if different from brand'),
    sa.Column('manufacturer', sa.String(length=150), nullable=True, comment='Manufacturing company name'),
    sa.Column('batch_prefix', sa.String(length=20), nullable=True, comment='Batch number prefix pattern used by the manufacturer'),
    sa.Column('salt_id', sa.Integer(), nullable=False, comment='Foreign key to the active pharmaceutical ingredient (salt)'),
    sa.Column('dosage_form', sa.String(length=50), nullable=True, comment='Form factor: Tablet, Capsule, Syrup, Injection, etc.'),
    sa.Column('strength', sa.String(length=50), nullable=True, comment="Potency specification (e.g., '500mg', '250mg/5ml')"),
    sa.Column('unit_price', sa.Float(precision=10, asdecimal=2), nullable=True, comment='Base unit price in INR (or configured currency)'),
    sa.Column('temperature_sensitive', sa.Boolean(), server_default='false', nullable=False, comment='Flag for cold-chain logistics: True if medicine requires temperature control'),
    sa.Column('min_storage_temp', sa.Float(precision=4, asdecimal=2), nullable=True, comment='Minimum storage temperature in Celsius (for cold-chain items)'),
    sa.Column('max_storage_temp', sa.Float(precision=4, asdecimal=2), nullable=True, comment='Maximum storage temperature in Celsius (for cold-chain items)'),
    sa.Column('description', sa.Text(), nullable=True, comment='Brief description or notes about the medicine'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Timestamp when this record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Timestamp when this record was last updated'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False, comment='Soft-delete flag. False = logically deleted.'),
    sa.ForeignKeyConstraint(['salt_id'], ['salts.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    comment='Brand-name medicines mapped to their active salt. Multiple brands per salt enable substitution when one brand is unavailable.'
    )
    op.create_index(op.f('ix_medicines_brand_name'), 'medicines', ['brand_name'], unique=False)
    op.create_index(op.f('ix_medicines_is_active'), 'medicines', ['is_active'], unique=False)
    op.create_index(op.f('ix_medicines_salt_id'), 'medicines', ['salt_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='Recipient of this notification'),
    sa.Column('title', sa.String(length=200), nullable=False, comment='Short notification title (shown in badge/list)'),
    sa.Column('message', sa.Text(), nullable=False, comment='Full notification message with details and recommended action'),
    sa.Column('severity', sa.Enum('CRITICAL', 'WARNING', 'INFO', name='notificationseverity'), nullable=False, comment='Alert severity: critical (red), warning (yellow), info (green)'),
    sa.Column('source', sa.Enum('EXPIRY_WATCHDOG', 'DEMAND_FORECAST', 'CLIMATE_ENGINE', 'REDISTRIBUTION', 'INVENTORY_ALERT', 'SYSTEM_SECURITY', 'TRANSFER_REQUEST', name='notificationsource'), nullable=False, comment='System component that generated this notification'),
    sa.Column('resource_type', sa.String(length=50), nullable=True, comment="Type of linked resource (e.g., 'inventory', 'transfer_request')"),
    sa.Column('resource_id', sa.Integer(), nullable=True, comment='ID of the linked resource for direct navigation'),
    sa.Column('action_url', sa.String(length=500), nullable=True, comment='Frontend URL to navigate to when notification is clicked'),
    sa.Column('is_read', sa.Boolean(), server_default='false', nullable=False, comment='Whether the user has read this notification'),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True, comment='When the user read/dismissed this notification'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True, comment='After this date, the notification can be auto-pruned'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Timestamp when this record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Timestamp when this record was last updated'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='In-app 3-tier notification system for real-time alerts. Sources: expiry watchdog, demand forecast, climate engine, etc.'
    )
    op.create_index('ix_notif_created', 'notifications', ['created_at'], unique=False)
    op.create_index('ix_notif_severity', 'notifications', ['severity'], unique=False)
    op.create_index('ix_notif_source', 'notifications', ['source'], unique=False)
    op.create_index('ix_notif_user_read', 'notifications', ['user_id', 'is_read'], unique=False)
    op.create_table('password_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='User whose password history this belongs to'),
    sa.Column('password_hash', sa.String(length=255), nullable=False, comment='Bcrypt hash of the previous password (same format as users.password_hash)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='When this password was set (and then changed)'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Historical password hashes to prevent reuse. Keeps the last N passwords per user. Immutable records.'
    )
    op.create_index('ix_ph_user_created', 'password_history', ['user_id', 'created_at'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False, comment='SHA-256 hash of the refresh token. Raw token is NEVER stored.'),
    sa.Column('token_family_id', sa.String(length=64), nullable=False, comment='Groups related tokens from the same login session. If theft is detected, the ENTIRE family is revoked.'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='Owner of this token'),
    sa.Column('is_revoked', sa.Boolean(), server_default='false', nullable=False, comment='Whether this token has been revoked'),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True, comment='When this token was revoked'),
    sa.Column('revoked_reason', sa.String(length=30), nullable=True, comment="Reason for revocation: 'rotation', 'logout', 'password_change', 'theft_detected', 'admin_revoke'"),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False, comment='When this token expires (absolute, not sliding)'),
    sa.Column('device_fingerprint', sa.String(length=255), nullable=True, comment='Hashed device identifier to detect unauthorized device reuse'),
    sa.Column('ip_address', sa.String(length=45), nullable=True, comment='IP address from which the token was issued (IPv6 capable)'),
    sa.Column('user_agent', sa.String(length=255), nullable=True, comment='Client user-agent at token issuance time'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Timestamp when this record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Timestamp when this record was last updated'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash'),
    comment='Secure refresh token storage with OWASP-compliant rotation. SHA-256 hashed, family-tracked, reuse-detected.'
    )
    op.create_index(op.f('ix_refresh_tokens_token_family_id'), 'refresh_tokens', ['token_family_id'], unique=False)
    op.create_index('ix_rt_expires', 'refresh_tokens', ['expires_at'], unique=False)
    op.create_index('ix_rt_family', 'refresh_tokens', ['token_family_id'], unique=False)
    op.create_index('ix_rt_token_hash', 'refresh_tokens', ['token_hash'], unique=True)
    op.create_index('ix_rt_user', 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('shop_staff',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='Reference to the user (pharmacist or admin)'),
    sa.Column('shop_id', sa.Integer(), nullable=False, comment='Reference to the assigned shop'),
    sa.Column('assigned_date', sa.Date(), server_default='CURRENT_DATE', nullable=False, comment='Date when the user was assigned to this shop'),
    sa.Column('is_primary', sa.Boolean(), server_default='false', nullable=False, comment="Whether this is the user's primary shop assignment"),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Timestamp when this record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Timestamp when this record was last updated'),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'shop_id', name='uq_shop_staff_user_shop'),
    comment='Maps pharmacists to their assigned shops. RBAC enforcement: users can only access inventory at assigned shops.'
    )
    op.create_index('ix_shopstaff_shop', 'shop_staff', ['shop_id'], unique=False)
    op.create_table('demand_forecasts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('med_id', sa.Integer(), nullable=False, comment='Medicine being forecasted'),
    sa.Column('shop_id', sa.Integer(), nullable=False, comment='Shop location for this forecast'),
    sa.Column('prediction_date', sa.Date(), nullable=False, comment='Date for which this prediction applies'),
    sa.Column('predicted_demand', sa.Float(precision=10, asdecimal=2), nullable=False, comment='Predicted number of units that will be consumed/sold'),
    sa.Column('current_stock', sa.Integer(), nullable=True, comment='Stock level at the time the forecast was generated'),
    sa.Column('stock_deficit', sa.Integer(), nullable=True, comment='predicted_demand - current_stock (negative = surplus, positive = deficit)'),
    sa.Column('confidence_score', sa.Float(precision=5, asdecimal=4), nullable=True, comment='Model confidence (0.0 to 1.0). Lower scores = less reliable predictions.'),
    sa.Column('model_version', sa.String(length=20), nullable=True, comment='Version/tag of the ML model that generated this forecast'),
    sa.Column('metadata_json', sa.Text(), nullable=True, comment='Additional model metadata (seasonal factors, feature importance, etc.)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Timestamp when this record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Timestamp when this record was last updated'),
    sa.ForeignKeyConstraint(['med_id'], ['medicines.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='ML-generated demand predictions. Updated periodically by the forecasting engine. Consumed by the dashboard and alerting system.'
    )
    op.create_index('ix_forecast_confidence', 'demand_forecasts', ['confidence_score'], unique=False)
    op.create_index('ix_forecast_date', 'demand_forecasts', ['prediction_date'], unique=False)
    op.create_index('ix_forecast_med_shop', 'demand_forecasts', ['med_id', 'shop_id'], unique=False)
    op.create_table('inventory',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Unique inventory record identifier'),
    sa.Column('med_id', sa.Integer(), nullable=False, comment='Foreign key to the medicine being tracked'),
    sa.Column('shop_id', sa.Integer(), nullable=False, comment='Foreign key to the shop holding this stock'),
    sa.Column('quantity', sa.Integer(), nullable=False, comment='Current stock quantity. Updated only via audited transactions.'),
    sa.Column('batch_number', sa.String(length=50), nullable=True, comment='Manufacturer batch number for traceability'),
    sa.Column('expiry_date', sa.Date(), nullable=False, comment='Date after which this stock MUST NOT be dispensed'),
    sa.Column('cost_price', sa.Float(precision=10, asdecimal=2), nullable=True, comment='Purchase cost per unit'),
    sa.Column('selling_price', sa.Float(precision=10, asdecimal=2), nullable=True, comment='Selling price per unit at this shop'),
    sa.Column('version_id', sa.Integer(), server_default='1', nullable=False, comment='Optimistic lock version. Auto-incremented on each UPDATE. Prevents race conditions in concurrent stock modifications.'),
    sa.Column('is_reserved', sa.Boolean(), server_default='false', nullable=False, comment='True if this batch is reserved for a pending transfer or order'),
    sa.Column('storage_location', sa.String(length=50), nullable=True, comment="Physical storage location identifier (e.g., 'Shelf-A3', 'Fridge-02')"),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Timestamp when this record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Timestamp when this record was last updated'),
    sa.ForeignKeyConstraint(['med_id'], ['medicines.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    comment='Real-time stock ledger. Each row represents one medicine batch at one shop location. Adjustments are audited, never deleted.'
    )
    op.create_index('ix_inventory_expiry', 'inventory', ['expiry_date'], unique=False)
    op.create_index(op.f('ix_inventory_expiry_date'), 'inventory', ['expiry_date'], unique=False)
    op.create_index(op.f('ix_inventory_med_id'), 'inventory', ['med_id'], unique=False)
    op.create_index('ix_inventory_med_quantity', 'inventory', ['med_id', 'quantity'], unique=False)
    op.create_index('ix_inventory_med_shop', 'inventory', ['med_id', 'shop_id'], unique=False)
    op.create_index(op.f('ix_inventory_shop_id'), 'inventory', ['shop_id'], unique=False)
    op.create_index('ix_inventory_shop_quantity', 'inventory', ['shop_id', 'quantity'], unique=False)
    op.create_table('stock_transfer_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('from_shop_id', sa.Integer(), nullable=False, comment='Source shop with excess stock'),
    sa.Column('to_shop_id', sa.Integer(), nullable=False, comment='Destination shop with shortage'),
    sa.Column('med_id', sa.Integer(), nullable=False, comment='Medicine being transferred'),
    sa.Column('inventory_id', sa.Integer(), nullable=True, comment='Specific inventory batch being transferred'),
    sa.Column('quantity_requested', sa.Integer(), nullable=False, comment='Number of units proposed for transfer'),
    sa.Column('quantity_transferred', sa.Integer(), nullable=True, comment='Actual number of units transferred (may differ after approval)'),
    sa.Column('reason', sa.Text(), nullable=True, comment='System-generated explanation for why this transfer was recommended'),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='transferpriority'), nullable=False, comment="Urgency level based on destination shop's shortage severity"),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'IN_TRANSIT', 'COMPLETED', 'REJECTED', 'CANCELLED', name='transferstatus'), nullable=False, comment='Current state of the transfer request'),
    sa.Column('approved_by', sa.Integer(), nullable=True, comment='Admin who approved the transfer'),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp of admin approval'),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp of physical transfer completion'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Timestamp when this record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Timestamp when this record was last updated'),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['from_shop_id'], ['shops.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['inventory_id'], ['inventory.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['med_id'], ['medicines.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['to_shop_id'], ['shops.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    comment='Stock redistribution requests generated by the Smart Redistribution Engine. Tracks the full lifecycle: suggestion → approval → transit → completion.'
    )
    op.create_index('ix_transfer_from', 'stock_transfer_requests', ['from_shop_id'], unique=False)
    op.create_index('ix_transfer_med', 'stock_transfer_requests', ['med_id'], unique=False)
    op.create_index('ix_transfer_status', 'stock_transfer_requests', ['status'], unique=False)
    op.create_index('ix_transfer_to', 'stock_transfer_requests', ['to_shop_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_transfer_to', table_name='stock_transfer_requests')
    op.drop_index('ix_transfer_status', table_name='stock_transfer_requests')
    op.drop_index('ix_transfer_med', table_name='stock_transfer_requests')
    op.drop_index('ix_transfer_from', table_name='stock_transfer_requests')
    op.drop_table('stock_transfer_requests')
    op.drop_index('ix_inventory_shop_quantity', table_name='inventory')
    op.drop_index(op.f('ix_inventory_shop_id'), table_name='inventory')
    op.drop_index('ix_inventory_med_shop', table_name='inventory')
    op.drop_index('ix_inventory_med_quantity', table_name='inventory')
    op.drop_index(op.f('ix_inventory_med_id'), table_name='inventory')
    op.drop_index(op.f('ix_inventory_expiry_date'), table_name='inventory')
    op.drop_index('ix_inventory_expiry', table_name='inventory')
    op.drop_table('inventory')
    op.drop_index('ix_forecast_med_shop', table_name='demand_forecasts')
    op.drop_index('ix_forecast_date', table_name='demand_forecasts')
    op.drop_index('ix_forecast_confidence', table_name='demand_forecasts')
    op.drop_table('demand_forecasts')
    op.drop_index('ix_shopstaff_shop', table_name='shop_staff')
    op.drop_table('shop_staff')
    op.drop_index('ix_rt_user', table_name='refresh_tokens')
    op.drop_index('ix_rt_token_hash', table_name='refresh_tokens')
    op.drop_index('ix_rt_family', table_name='refresh_tokens')
    op.drop_index('ix_rt_expires', table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_family_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index('ix_ph_user_created', table_name='password_history')
    op.drop_table('password_history')
    op.drop_index('ix_notif_user_read', table_name='notifications')
    op.drop_index('ix_notif_source', table_name='notifications')
    op.drop_index('ix_notif_severity', table_name='notifications')
    op.drop_index('ix_notif_created', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_medicines_salt_id'), table_name='medicines')
    op.drop_index(op.f('ix_medicines_is_active'), table_name='medicines')
    op.drop_index(op.f('ix_medicines_brand_name'), table_name='medicines')
    op.drop_table('medicines')
    op.drop_index('ix_climate_alert_shop', table_name='climate_alerts')
    op.drop_index('ix_climate_alert_risk', table_name='climate_alerts')
    op.drop_index('ix_climate_alert_date', table_name='climate_alerts')
    op.drop_table('climate_alerts')
    op.drop_index('ix_audit_user', table_name='audit_logs')
    op.drop_index('ix_audit_timestamp', table_name='audit_logs')
    op.drop_index('ix_audit_resource', table_name='audit_logs')
    op.drop_index('ix_audit_action', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_shops_pincode'), table_name='shops')
    op.drop_index(op.f('ix_shops_is_active'), table_name='shops')
    op.drop_index(op.f('ix_shops_code'), table_name='shops')
    op.drop_index(op.f('ix_shops_city'), table_name='shops')
    op.drop_table('shops')
    op.drop_index(op.f('ix_salts_is_active'), table_name='salts')
    op.drop_index(op.f('ix_salts_formula_name'), table_name='salts')
    op.drop_index(op.f('ix_salts_category'), table_name='salts')
    op.drop_index('ix_salt_abc_class', table_name='salts')
    op.drop_table('salts')
    # ### end Alembic commands ###
